# Generated by Django 4.1 on 2022-08-26 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crime_id', models.CharField(max_length=255)),
                ('original_crime_type_name', models.CharField(max_length=255)),
                ('report_date', models.DateTimeField(null=True)),
                ('call_date', models.DateTimeField(null=True)),
                ('offense_date', models.DateTimeField(null=True)),
                ('call_time', models.TimeField(null=True)),
                ('call_date_time', models.DateTimeField(null=True)),
                ('disposition', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('agency_id', models.CharField(max_length=255)),
                ('address_type', models.CharField(max_length=255)),
                ('common_location', models.CharField(default='', max_length=255)),
            ],
        ),
    ]
